### ISSUE TITLE
When generating TSV, garbage row is created.

### ISSUE THREAD

**Issue by benedictchen** [katspaugh/kuromoji-gloss#2]
I expected 3 rows, but a third row of garbage with all the words are loaded for some odd reason.  Please see screenshot.

<img width="939" alt="screen shot 2017-03-06 at 8 48 39 pm" src="https://cloud.githubusercontent.com/assets/1243495/23608793/6252d84c-02ae-11e7-8973-ad28002d16b7.png">

**Comment by katspaugh** [comment]
It's not garbage, it's context! 😆 

The last column is the sentence in which a word was encountered: https://github.com/katspaugh/kuromoji-gloss/blob/master/src/services/csv.js#L7

If you're an Anki user, you can use this column for cloze tests, for instance. The idea is to produce the same format as [here](https://fluentcards.com/books/B00NW01MKM).

**Comment by benedictchen** [comment]
Oh, haha I see :-).
